/**
 * Boot-time migration runner.
 *
 * Applies the SQL migrations in ./drizzle (generated by drizzle-kit) and then
 * seeds static reference data. Both steps are idempotent, so this runs on
 * every boot (container entrypoint in production, instrumentation/dev boot
 * later phases).
 */
import path from 'path';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { getDb } from './index';
import { seedReferenceRanges } from './seed-reference-ranges';

export function runMigrations(migrationsFolder?: string): void {
  const folder =
    migrationsFolder ??
    process.env.DRIZZLE_MIGRATIONS_DIR ??
    path.join(process.cwd(), 'drizzle');
  const db = getDb();
  migrate(db, { migrationsFolder: folder });
  seedReferenceRanges(db);
}
