import { AVAILABLE_SCOPES } from '@/lib/api-auth';

export const dynamic = 'force-static';

export async function GET() {
  const scopes = AVAILABLE_SCOPES.map((s) => ({
    value: s.value,
    label: s.label,
    description: s.description,
  }));

  return Response.json({
    api: 'HealthTracker API v1',
    version: '1.0.0',
    auth: 'Bearer token in Authorization header. Format: Bearer ohts_pat_...',
    docs: '/docs/api',
    openapi: '/api/v1/openapi.json',
    endpoints: [
      {
        path: '/api/v1/metrics',
        method: 'GET',
        scope: null,
        params: [],
        description: 'Metric registry as JSON (public, no auth)',
      },
      {
        path: '/api/v1/openapi.json',
        method: 'GET',
        scope: null,
        params: [],
        description: 'OpenAPI 3.1 document (public, no auth)',
      },
      {
        path: '/api/v1/medications',
        method: 'GET',
        scope: 'read:medications',
        params: ['include_inactive'],
        description: 'List medications (active only by default)',
      },
      {
        path: '/api/v1/conditions',
        method: 'GET',
        scope: 'read:conditions',
        params: [],
        description: 'List medical conditions',
      },
      {
        path: '/api/v1/allergies',
        method: 'GET',
        scope: 'read:allergies',
        params: [],
        description: 'List allergies',
      },
      {
        path: '/api/v1/vitals',
        method: 'GET',
        scope: 'read:vitals',
        params: ['metric', 'days', 'from', 'to', 'limit'],
        description: 'List vital signs',
      },
      {
        path: '/api/v1/vitals',
        method: 'POST',
        scope: 'write:vitals',
        params: [],
        description: 'Upsert one vital record (idempotent on metric/day/source)',
      },
      {
        path: '/api/v1/vitals/batch',
        method: 'POST',
        scope: 'write:vitals',
        params: [],
        description: 'Upsert up to 500 vital records in one transaction',
      },
      {
        path: '/api/v1/vitals/latest',
        method: 'GET',
        scope: 'read:vitals',
        params: ['metrics'],
        description: 'Latest reading per metric (?metrics=a,b,c)',
      },
      {
        path: '/api/v1/workouts',
        method: 'GET',
        scope: 'read:fitness',
        params: ['from', 'to', 'type', 'label', 'limit'],
        description: 'List workout sessions with nested entries',
      },
      {
        path: '/api/v1/workouts',
        method: 'POST',
        scope: 'write:fitness',
        params: [],
        description: 'Create a workout session (+ entries); 409 carries the existing session on started_at collision',
      },
      {
        path: '/api/v1/workouts/{id}',
        method: 'GET',
        scope: 'read:fitness',
        params: [],
        description: 'Get one workout session',
      },
      {
        path: '/api/v1/workouts/{id}',
        method: 'PATCH',
        scope: 'write:fitness',
        params: [],
        description: 'Correct a session (partial fields; entries = full replacement)',
      },
      {
        path: '/api/v1/workouts/{id}',
        method: 'DELETE',
        scope: 'write:fitness',
        params: [],
        description: 'Delete a session (entries cascade)',
      },
      {
        path: '/api/v1/exercises',
        method: 'GET',
        scope: 'read:fitness',
        params: ['review_status'],
        description: 'List the exercise catalog',
      },
      {
        path: '/api/v1/exercises',
        method: 'POST',
        scope: 'write:fitness',
        params: [],
        description: 'Create a catalog entry',
      },
      {
        path: '/api/v1/exercises/{id}',
        method: 'PATCH',
        scope: 'write:fitness',
        params: [],
        description: 'Edit a catalog entry (rename/alias/confirm)',
      },
      {
        path: '/api/v1/exercises/{id}/history',
        method: 'GET',
        scope: 'read:fitness',
        params: ['limit'],
        description: 'Recent entries for one exercise, newest session first',
      },
      {
        path: '/api/v1/checkins',
        method: 'GET',
        scope: 'read:fitness',
        params: ['from', 'to', 'limit'],
        description: 'List weekly check-ins',
      },
      {
        path: '/api/v1/checkins/{weekStart}',
        method: 'GET',
        scope: 'read:fitness',
        params: [],
        description: "Get one week's check-in (weekStart = Monday YYYY-MM-DD)",
      },
      {
        path: '/api/v1/checkins/{weekStart}',
        method: 'PUT',
        scope: 'write:fitness',
        params: [],
        description: 'Upsert the manual check-in fields (neck_in/waist_in write through to vitals)',
      },
      {
        path: '/api/v1/weeks/{weekStart}',
        method: 'GET',
        scope: 'read:fitness',
        params: [],
        description: 'Computed weekly rollup (sessions, body/recovery averages, goal progress, deltas)',
      },
      {
        path: '/api/v1/goals',
        method: 'GET',
        scope: 'read:fitness',
        params: ['active', 'kind'],
        description: 'List goals',
      },
      {
        path: '/api/v1/goals',
        method: 'POST',
        scope: 'write:fitness',
        params: [],
        description: 'Create a metric or frequency goal',
      },
      {
        path: '/api/v1/goals/{id}',
        method: 'PATCH',
        scope: 'write:fitness',
        params: [],
        description: 'Edit a goal (kind is immutable)',
      },
      {
        path: '/api/v1/labs',
        method: 'GET',
        scope: 'read:labs',
        params: ['test', 'days'],
        description: 'List lab results',
      },
      {
        path: '/api/v1/procedures',
        method: 'GET',
        scope: 'read:procedures',
        params: [],
        description: 'List procedures',
      },
      {
        path: '/api/v1/vaccines',
        method: 'GET',
        scope: 'read:vaccines',
        params: [],
        description: 'List vaccine records',
      },
      {
        path: '/api/v1/providers',
        method: 'GET',
        scope: 'read:providers',
        params: [],
        description: 'List healthcare providers',
      },
      {
        path: '/api/v1/profile',
        method: 'GET',
        scope: 'read:profile',
        params: [],
        description: 'Get user profile (DOB, height, weight, etc.)',
      },
      {
        path: '/api/v1/summary',
        method: 'GET',
        scope: 'read:all',
        params: [],
        description: 'Full health summary — all data in one call',
      },
    ],
    scopes,
  });
}
